webdrive/pro1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^share/', include('share.urls', namespace='share')),
]

webdrive/share/urls.py
from django.conf.urls import url

from . import views
from . import api

urlpatterns = [
    url(r'^(?:^page/(?P<page>[0-9]+)/)?$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^list/(?P<pk>[0-9a-z]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.list_dir, name='list_dir'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^view/(?P<pk>[0-9]+)/$', views.view, name='view'),
    url(r'^download/(?P<pk>[0-9]+)/$', views.download, name='download'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete, name='delete'),
    url(r'^share/list/(?:page/(?P<page>[0-9]+)/)?$', views.list_shares, name='list_shares'),
    url(r'^share/create/(?P<pk>[0-9]+)/$', views.create_share, name='create_share'),
    url(r'^share/edit/(?P<pk>[0-9]+)/$', views.edit_share, name='edit_share'),
    url(r'^share/delete/(?P<pk>[0-9]+)/$', views.delete_share, name='delete_share'),
    url(r'^post_code/(?P<pk>[0-9]+)/$', views.post_code, name='post_code'),
    url(r'^captcha/', views.gen_captcha, name='gen_captcha'),
    url(r'^search/', views.search, name='search'),
    url(r'^upload/', views.upload, name='upload'),
    url(r'^api/login/', api.login, name='api_login'),
    url(r'^api/inform_login/', api.inform_login, name='api_inform_login'),
    url(r'^api/ls/', api.ls, name='api_ls'),
    url(r'^api/mkdir/', api.mkdir, name='api_mkdir'),
    url(r'^api/rmdir/', api.rmdir, name='api_rmdir'),
    url(r'^api/exists/', api.exists, name='api_exists'),
]

webdrive/share/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    captcha = forms.CharField(max_length=12)


class RenameForm(forms.Form):
    name = forms.CharField()


class ShareForm(forms.Form):
    code = forms.CharField(max_length=8, min_length=6, required=False)
    expire = forms.DateTimeField(required=False, disabled=True)
    anonymous = forms.BooleanField(required=False)
    never_expire = forms.BooleanField(required=False, initial=True)


class UploadForm(forms.Form):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

webdrive/share/views.py
import os
import re
import hashlib
from io import BytesIO
from tempfile import NamedTemporaryFile

from django.shortcuts import render, get_object_or_404
from django import urls
from django.urls import reverse
from django.http import (HttpResponseRedirect, StreamingHttpResponse,
                         HttpResponseBadRequest, HttpResponse, Http404)
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import LoginForm, RenameForm, ShareForm, UploadForm
from .models import DirectoryFile, RegularFile, File, Share
from .libs import make_abspath, gen_code
from .views_libs import (create_directory, get_session_id,
                         get_session_data, set_session_data,
                         share_approved, permission_ok, make_image, gentext,
                         make_path, get_items)


@login_required
def index(request, page=1):
    """
    用户主页，显示用户资源的相关链接：文件，共享。
    """
    user = request.user
    home = get_object_or_404(File, name=user.username, owner=user,
                             is_regular=False, parent=None)
    return list_dir(request, dir=home, page=page)


@login_required
def list_dir(request, pk=None, dir=None, page=1):
    """查看目录下的文件"""
    assert pk is not None or dir is not None, "pk or dir is required"
    if dir is None:
        user = request.user
        dir = get_object_or_404(File, pk=pk, owner=user)
    files, parents = get_items(dir)

    # 分页
    paginator = Paginator(files, settings.PAGE_SIZE)
    try:
        files = paginator.page(page)
    except PageNotAnInteger:
        # 如果page不是整数，就选择第一页
        files = paginator.page(1)
    except EmptyPage:
        # 如果page超出范围，比如说9999, 就选择最后一页
        files = paginator.page(paginator.num_pages)

    context = {'files': files, 'parents': parents, 'title': 'File list'}
    return render(request, 'share/list_dir.html', context=context)

@require_POST
def post_code(request, pk):
    file = get_object_or_404(File, pk=pk)
    if request.method == 'POST':
        code = request.POST['code']
        for share, _ in file.shares():
            if share.code == code:
                shares = get_session_data(request, 'shares') or []
                shares.append(share.pk)
                set_session_data(request, 'shares', shares)
                url = reverse('share:detail', args=(pk,))
                return HttpResponseRedirect(url)
        return HttpResponse('invalid code')


def detail(request, pk):
    """查看文件详情"""
    file = get_object_or_404(File, pk=pk)
    if file.is_regular and not file.object.finished:
        raise Http404('No File matches the given query')

    context = {'file': file}
    if request.user.is_authenticated():
        # 登录用户，显示所有信息
        template_file = "share/detail.html"
        context['title'] = 'File detail'
    elif file.shared_to_all():
        # 匿名共享文件，显示基本信息及下载链接
        template_file = "share/detail_share_to_all.html"
        context['title'] = 'Shared file info'
    elif file.shared_with_code():
        # 分享码共享文件，显示基本信息，
        # 如果已经提交了有效的分享码，就显示链接，
        # 否则，就显示提交分享码的表单
        template_file = "share/detail_share_with_code.html"
        context['title'] = 'Shared file info'
        context['approved'] = share_approved(request, file)
    else:
        url = reverse('share:login') + '?next=' + request.META['PATH_INFO']
        return HttpResponseRedirect(url)
    return render(request, template_file, context=context)


def view(request, pk):
    """查看文件内容"""
    file = get_object_or_404(File, pk=pk)
    if file.is_regular and not file.object.finished:
        raise Http404('No File matches the given query')

    if not permission_ok(request, file):
        url = reverse('share:login') + '?next=' + request.META['PATH_INFO']
        return HttpResponseRedirect(url)

    if file.is_viewable():
        abspath = make_abspath(file.object.path)
        buf = open(abspath, 'rb')
        response = StreamingHttpResponse(buf)
        response['Content-Type'] = file.raw_mimetype()
        return response
    else:
        context = {'file': file, 'title': 'View file content'}
        return render(request, 'share/view.html', context=context)


def download(request, pk):
    """下载文件"""
    file = get_object_or_404(File, pk=pk)
    if file.is_regular and not file.object.finished:
        raise Http404('No File matches the given query')

    if not permission_ok(request, file):
        url = reverse('share:login') + '?next=' + request.META['PATH_INFO']
        return HttpResponseRedirect(url)

    if not file.is_regular:
        return HttpResponseBadRequest("Only a regular file can be downloaded.")

    abspath = make_abspath(file.object.path)
    buf = open(abspath, 'rb')
    response = StreamingHttpResponse(buf)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Length'] = str(file.object.size)
    response['Content-Disposition'] = 'attachment;filename="%s"' % file.name
    return response


@login_required
def list_shares(request, page=1):
    """查看所有的共享"""
    user = request.user
    now = timezone.now()
    shares = Share.objects.filter(target__owner=user)
    shares = [x for x in shares if not x.is_expired()]
    shares = sorted(shares, key=(lambda x: x.target.is_regular))

    # 分页
    paginator = Paginator(shares, settings.PAGE_SIZE)
    try:
        shares = paginator.page(page)
    except PageNotAnInteger:
        # 如果page不是整数，就选择第一页
        shares = paginator.page(1)
    except EmptyPage:
        # 如果page超出范围，比如说9999, 就选择最后一页
        shares = paginator.page(paginator.num_pages)

    context = {'shares': shares, 'title': 'Share list'}
    return render(request, 'share/list_shares.html', context=context)


@login_required
def create_share(request, pk):
    """共享文件"""
    file = get_object_or_404(File, pk=pk)
    if file.is_regular and not file.object.finished:
        raise Http404('No File matches the given query')

    if request.method == 'POST':
        form = ShareForm(request.POST)
        form.errors.clear()
        try:
            if 'anonymous' in request.POST:
                code = None
            else:
                code = form['code'].field.clean(request.POST['code'])
        except ValidationError as e:
            form.add_error('code', e)
        try:
            if 'never_expire' in request.POST:
                expire = None
            else:
                expire = form['expire'].field.clean(request.POST['expire'])
        except ValidationError as e:
            form.add_error('expire', e)

        if not form.errors:
            Share.objects.create(target=file, code=code, expire=expire)
            url = reverse('share:detail', args=(pk,))
            return HttpResponseRedirect(url)

        form['code'].field.disabled = 'anonymous' in request.POST
        form['expire'].field.disabled = 'never_expire' in request.POST
    else:
        form = ShareForm(initial={'code': gen_code()})

    notice = ('note: if you share a directory, all files under '
              'the directory tree will be shared.')
    context={'file_name': file.name, 'form': form,
             'notice': notice, 'title': 'Create share'}
    return render(request, 'share/create_share.html', context=context)


@login_required
def edit_share(request, pk):
    """修改共享"""
    share = get_object_or_404(Share, pk=pk)
    if request.method == 'POST':
        form = ShareForm(request.POST)
        form.errors.clear()
        try:
            if 'anonymous' in request.POST:
                code = None
            else:
                code = form['code'].field.clean(request.POST['code'])
        except ValidationError as e:
            form.add_error('code', e)
        try:
            if 'never_expire' in request.POST:
                expire = None
            else:
                expire = form['expire'].field.clean(request.POST['expire'])
        except ValidationError as e:
            form.add_error('expire', e)

        if not form.errors:
            share.code = code
            share.expire = expire
            share.save()
            next_url = request.POST['next']
            return HttpResponseRedirect(next_url)

        form['code'].field.disabled = 'anonymous' in request.POST
        form['expire'].field.disabled = 'never_expire' in request.POST
    else:
        init_data = {'code': share.code, 'expire': share.expire,
                     'anonymous': share.code is None,
                     'never_expire': share.expire is None}
        form = ShareForm(initial=init_data)
        form['code'].field.disabled = init_data['anonymous']
        form['expire'].field.disabled = init_data['never_expire']

    next_url = request.META['HTTP_REFERER']
    context={'file_name': share.target.name, 'form': form,
             'next': next_url, 'title': 'Edit share'}
    return render(request, 'share/create_share.html', context=context)


@login_required
def delete_share(request, pk):
    """删除共享"""
    share = get_object_or_404(Share, pk=pk)
    if request.method == 'POST':
        if request.POST.get('submit', '') == 'Delete':
            share.delete()
            return HttpResponseRedirect(request.POST['next'])
    next_url = request.META['HTTP_REFERER']
    context={'file_name': share.target.name, 'next': next_url,
             'title': 'Delete share'}
    return render(request, 'share/delete_share.html', context=context)


@login_required
def edit(request, pk):
    """修改文件"""
    file = get_object_or_404(File, pk=pk)
    if file.is_regular and not file.object.finished:
        raise Http404('No File matches the given query')

    if request.method == 'POST':
        form = RenameForm(request.POST)
        if form.is_valid():

webdrive/share/templates/share/base.html
{% load static %}
<html>
<head>
<title>{{ title }}</title>
<link rel="stylesheet" href="{% static 'share/css/main.css' %}" />
</head>
<body>

{% include "share/header.html" %}

{% block content %}
{% endblock %}

{% include "share/footer.html" %}

</body>
</html>

webdrive/share/templates/share/delete.html
{% extends "share/base.html" %}

{% block content %}
<p>Delete: {{ file_name }}</p>
<form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}">
  <input type="submit" name="submit" value="Delete">
  <input type="button" value="Cancel" onclick="window.history.back();">
</form>
{% endblock %}

webdrive/share/templates/share/delete_share.html
{% extends "share/base.html" %}

{% block content %}
<p>Delete share for: {{ file_name }}</p>
<form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}">
  <input type="submit" name="submit" value="Delete">
  <input type="button" value="Cancel" onclick="window.history.back();">
</form>
{% endblock %}

webdrive/share/templates/share/detail_share_to_all.html
{% extends "share/base.html" %}

{% block content %}

<table>
  <tr><td>Name:</td><td>{{ file.name }}</td></tr>
  <tr><td>Size:</td><td>{{ file.object.size }}</td></tr>
  <tr><td>Time:</td><td>{{ file.object.time|date:"Y-m-d H:m" }}</td></tr>
  <tr><td>Digest:</td><td>{{ file.object.digest }}</td></tr>
  <tr>
      <td>Operation:</td>
      <td class="operation2" colspan=2>
        <a href="{% url 'share:view' file.pk %}">view</a> |
        <a href="{% url 'share:download' file.pk %}">download</a>
      </td>
  </tr>
</table>
{% endblock %}

webdrive/share/templates/share/detail_share_with_code.html
{% extends "share/base.html" %}

{% block content %}

<table>
  <tr><td>Name:</td><td>{{ file.name }}</td></tr>
  <tr><td>Size:</td><td>{{ file.object.size }}</td></tr>
  <tr><td>Time:</td><td>{{ file.object.time|date:"Y-m-d H:m" }}</td></tr>
  <tr><td>Digest:</td><td>{{ file.object.digest }}</td></tr>
{% if approved %}
  <tr>
      <td>Operation:</td>
      <td class="operation2" colspan=2>
        <a href="{% url 'share:view' file.pk %}">view</a> |
        <a href="{% url 'share:download' file.pk %}">download</a>
      </td>
  </tr>
{% else %}
  <tr><td colspan=2>
  <strong>Enter code to access the file</strong>
  <form method="post" action="{% url 'share:post_code' file.pk %}">
    {% csrf_token %}
    <input name="code">
    <input type="submit" value="OK">
  </form>
  </td></tr>
{% endif %}
</table>
{% endblock %}

webdrive/share/templates/share/edit.html
{% extends "share/base.html" %}

{% block content %}
<form method="post">
{% csrf_token %}
  <table>
  {{ form }}
  <tr><td colspan=2><input type="submit" value="Rename"></td></tr>
  </table>
</form>
{% endblock %}

webdrive/share/templates/share/footer.html
<hr></hr>
<h4>webmaster: admin@share.com</h4>

webdrive/share/templates/share/header.html
<div class="header">
  <div class="title">{{ title }}</div>

{% if login_page == True %}
  <div class="fast_access">
    <small><a href="{% url 'share:signup' %}">signup</a></small>
  </div>
{% else %}
  <div class="fast_access">
  {% if request.user.is_authenticated %}
    <form action="{% url 'share:search' %}">
      <input name="pattern" value="{{ pattern }}" placeholder="Enter a regular expression">
    </form>
    <small>
    <a href="{% url 'share:index' %}">files</a> |
    <a href="{% url 'share:list_shares' %}">shares</a> |
    <a href="{% url 'share:logout' %}">logout</a>
    </small>
  {% else %}
    <small><a href="{% url 'share:login' %}">login</a></small>
  {% endif %}
  </div>
{% endif %}

</div>

webdrive/share/templates/share/list_dir.html
{% extends "share/base.html" %}
{% load static %}

{% block content %}

<div class="path">
  {% for parent in parents %}
    {% if forloop.last %}
    <span>/ {{ parent.name }}</span>
    {% else %}
    <span>/ <a href="{% url 'share:list_dir' parent.pk %}">{{ parent.name }}</a></span>
    {% endif %}
  {% endfor %}

  [ <a href="{% url 'share:upload' %}">upload to this directory</a> ]
</div>

<hr>

<table>
  {% for file in files %}
  <tr>
    <td><img src="{% static 'share/icons' %}/{{ file.mimetype }}.png"></td>
    <td>
      {% if file.is_regular %}
      <a href="{% url 'share:detail' file.pk %}">{{ file.name }}</a>
      {% else %}
      <a href="{% url 'share:list_dir' file.pk %}">{{ file.name }}</a>
      {% endif %}
    </td>
    <td class="size">{{ file.object.size }}</td>
    <td class="time">{{ file.object.time|date:"Y-m-d H:m" }}</td>
    <td class="operation">
      <a href="{% url 'share:detail' file.pk %}">detail</a> |
      <a href="{% url 'share:view' file.pk %}">view</a> |
      <a href="{% url 'share:download' file.pk %}">download</a> |
      <a href="{% url 'share:edit' file.pk %}">edit</a> |
      <a href="{% url 'share:create_share' file.pk %}">share</a> |
      <a href="{% url 'share:delete' file.pk %}">delete</a>
    </td>
  </tr>
  {% endfor %}
</table>

<div class="pagination">
    <span class="step-links">
        {% if files.has_previous %}
            <a href="{% url 'share:list_dir' files.0.parent.pk files.previous_page_number %}">&lt;&lt;</a>
        {% endif %}

        <span class="current">
            Page {{ files.number }}/{{ files.paginator.num_pages }}
        </span>

        {% if files.has_next %}
            <a href="{% url 'share:list_dir' files.0.parent.pk files.next_page_number %}">&gt;&gt;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

webdrive/share/templates/share/list_shares.html
{% extends "share/base.html" %}
{% load static %}

{% block content %}

<table>
  {% for share in shares %}
  <tr>
    <td><img src="{% static 'share/icons' %}/{{ share.target.mimetype }}.png"></td>
    <td>{{ share.target.name }}</td>
    <td class="code">{{ share.code|default:'[anonymous]' }}</td>
    <td class="time">{{ share.expire|date:"Y-m-d H:m"|default:'[indefinite]' }}</td>
    <td class="size">{{ share.target.object.size }}</td>
    <td class="time">{{ share.target.object.time|date:"Y-m-d H:m" }}</td>
    <td class="operation">
      <a href="{% url 'share:edit_share' share.pk %}">edit</a> |
      <a href="{% url 'share:delete_share' share.pk %}">delete</a>
    </td>
  </tr>
  {% endfor %}
</table>

<div class="pagination">
    <span class="step-links">
        {% if shares.has_previous %}
            <a href="{% url 'share:list_shares' shares.previous_page_number %}">&lt;&lt;</a>
        {% endif %}

        <span class="current">
            Page {{ shares.number }}/{{ shares.paginator.num_pages }}
        </span>

        {% if shares.has_next %}
            <a href="{% url 'share:list_shares' shares.next_page_number %}">&gt;&gt;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

webdrive/share/templates/share/login.html
{% extends "share/base.html" %}
{% load static %}

{% block content %}
<form method="post">
{% csrf_token %}
  <table>
  {{ form }}
  <tr><td></td><td><img id='captcha' src="{% url 'share:gen_captcha' %}"></td></tr>
  <tr><td colspan=2><input type="submit" value="Login"></td></tr>
  </table>
</form>

<script type="text/javascript" src="{% static 'share/js/jquery.min.js' %}"></script>
<script>
function reload_img() {
  $('#captcha').attr('src', "{% url 'share:gen_captcha' %}" + String(Math.random()));
}
$(document).ready(function() {
    $('#captcha').click(reload_img);
});
</script>

{% endblock %}

webdrive/share/templates/share/search.html
{% extends "share/base.html" %}
{% load static %}

{% block content %}

<table>
  {% for file in files %}
  <tr>
    <td><img src="{% static 'share/icons' %}/{{ file.mimetype }}.png"></td>
    <td>
      {% if file.is_regular %}
      <a href="{% url 'share:detail' file.pk %}">{{ file.name }}</a>
      {% else %}
      <a href="{% url 'share:list_dir' file.pk %}">{{ file.name }}</a>
      {% endif %}
    </td>
    <td class="size">{{ file.object.size }}</td>
    <td class="time">{{ file.object.time|date:"Y-m-d H:m" }}</td>
    <td class="operation">
      <a href="{% url 'share:detail' file.pk %}">detail</a> |
      <a href="{% url 'share:view' file.pk %}">view</a> |
      <a href="{% url 'share:download' file.pk %}">download</a> |
      <a href="{% url 'share:edit' file.pk %}">edit</a> |
      <a href="{% url 'share:create_share' file.pk %}">share</a> |
      <a href="{% url 'share:delete' file.pk %}">delete</a>
    </td>
  </tr>
  {% endfor %}
</table>

<div class="pagination">
    <span class="step-links">
        {% if files.has_previous %}
          <a href="?{{ qs }}&page={{ files.previous_page_number }}">&lt;&lt;</a>
        {% endif %}

        <span class="current">
            Page {{ files.number }}/{{ files.paginator.num_pages }}
        </span>

        {% if files.has_next %}
            <a href="?{{ qs }}&page={{ files.next_page_number }}">&gt;&gt;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

webdrive/share/templates/share/signup.html
{% extends "share/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign up">
  </form>
{% endblock %}

webdrive/share/templates/share/upload.html
{% extends "share/base.html" %}
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}">
  <table>
  {{ form }}
  <tr><td></td><td><input type="submit" value="Upload"></td></tr>
  </table>
</form>

{% endblock %}